### ISSUE TITLE
Implementing event emitters

### ISSUE THREAD

**Issue by Cadienvan** [Cadienvan/expirables#11]
Hey @mateonunez , wanted to share with you something I had in my mind for quite some time.
What about bringing some event emission inside the expirable data structures? That would provide a wider usage of those.

What do you think? Any idea about the implementation?

**Comment by mateonunez** [comment]
Hi, @Cadienvan. I'm not convinced to implement EventEmited at all. The idea sounds great, but what about implementing a hook system like `async-cache-dedupe` or `Fastify`? 

It could be useful when you need to exec statements before/after that ds expires.

Something like:

```js
dataStructure.addHook('onExpired', (...) => {})
```
or
```js
datastructure.addHook('berofeExpire', (...) => {})
```
> That determines the action before the ds expired

Or passing them as properties

```js
const set = ExpirableSet(..., {
  onExpired: (item, ...args) => {},
  beforeExpire: (item, ...args) => {}
}
```

**Comment by Cadienvan** [comment]
Yeah, sure, sounds good, that's what I was thinking about.

**Comment by mateonunez** [comment]
What types of hooks did you want to implement?

**Comment by Cadienvan** [comment]
They will surely depend on the data structure , yet onExpired and beforeExpire will be library wide

**Comment by Cadienvan** [comment]
I'll try to bring in a PR during the week

**Comment by mateonunez** [comment]
Glad to test it or review it. 🤗
