### ISSUE TITLE
Migrate Jest to tap

### ISSUE THREAD

**Issue by mateonunez** [Cadienvan/expirables#13]
Hi @Cadienvan, the project currently uses Jest as the test framework, which is a bit complex with running a single test. What do you think about replacing Jest with node-tap?

Also, I would add coverage using c8 and may achieve full project coverage. This will allow contributors to implement new features safely and with as few regressions as possible.

**Comment by Cadienvan** [comment]
Hey @mateonunez,
I never tried moving from Jest to Tap, yet this project could be small enough to try it out.

What could be the advantages and the drawbacks?

**Comment by Cadienvan** [comment]
@rollsappletree FYI.

**Comment by mateonunez** [comment]
For sure! 

- Tap is lightweight and easy-to-use. It is simple to set up and has a minimalistic approach to testing
- Parallel testing, tests can be run at the same time. This can significantly reduce the time it takes to run a large test suite.
- Isolated execution, tests can be run avoiding the tap CLI, that means you can easily run your test or suite with Node: "node test/example.js/"
- Reduce of testing time execution, as mentioned node-tap is lightweight and has no dependencies. The time of execution is faster than other frameworks.

These are some pros between tap and jest. The effort to migrate is really cheap. Tap and Jest has similar syntax and it's really easy to use.

**Comment by rollsappletree** [comment]
Could be a nice experiment, even to decide which testing framework we want to use in the future...

Very nice guys!

**Comment by Cadienvan** [comment]
So I guess we could go, @mateonunez wanna be the hero of this story?
Some of my colleagues are currently working on implementing hooks for other data structures, so I guess we could wait for it before moving to Tap so we do this work only once, seems good?

**Comment by mateonunez** [comment]
I think we need to discuss about the full coverage.

Full coverage will allow the project to be more stable and give superpowers to each new feature by highlighting uncovered cases. Sometimes full coverage can be tedious and tiring, but by implementing TDD the effort is less than implementing test after feature.

By requiring full coverage by default, we will force contributors to create a test for their PR. This checking can be done in the git hooks and also in the CI.

WDYT?

CC: @Cadienvan, @rollsappletree

**Comment by Cadienvan** [comment]
**I completely agree**, this library is small enough to allow for a PR to be followed by a test.
I'm not sure about 100%, there could be cases where testing a certain edge would be just tedious and would not provide any improvement.

We could still go with 100% if you, as I saw, are reaching this goal during the refactoring, then we could tweak it if we see some cases mentioned above!
