### ISSUE TITLE
Project Logo

### ISSUE THREAD

**Issue by Cadienvan** [Cadienvan/expirables#22]
![expirables](https://user-images.githubusercontent.com/5492927/235296305-b649fabe-b5af-4356-b0bf-a2fc622b4722.svg)
@mateonunez @rollsappletree @PellegrinoDurante @abettini hey guys I looked for some cool logo generators around the web and found this one out, I really like it, what do you think

**Comment by rollsappletree** [comment]
I love it! which generator did you use?

**Comment by mateonunez** [comment]
Really niceee! 👀

Have you ever think about a documentation page using Docusaurus, Nextra, etc?

**Comment by Cadienvan** [comment]
Can't remember, something like "Logo AI Generator"

@mateonunez I though about using Docusaurus but didn't see any added value leveraging that instead of the GitHub repo homepage, would you suggest doing it?

**Comment by mateonunez** [comment]
> @mateonunez I though about using Docusaurus but didn't see any added value leveraging that instead of the GitHub repo homepage, would you suggest doing it?

I think there is a lot of added value in having a dedicated page for documentation: possibility to go deeper into a topic while avoiding writing too much on the readme. You could also create a page dedicated to use cases or concrete examples of implementation, also but not least, it is always nice to have a dedicated page. 😁

**Comment by Cadienvan** [comment]
I guess we could go for it, maybe we could open a specific issue for this?
We could achieve it in two steps: First we could move current MD to Docusaurus and then improve it.

I don't know when I'll have the time for it but surely it's a task for everyone willing to contribute to the project, considering our live event some days ago where people asked how to contribute!

**Comment by Cadienvan** [comment]
Logo is out, it isn't the best logo ever seen yet it provides some coolness to the project ahah
Opened #23 for Docusaurus, may we close this one? @rollsappletree @mateonunez @PellegrinoDurante @abettini

**Comment by mateonunez** [comment]
Closed by https://github.com/Cadienvan/expirables/commit/19572127caa4a96fe5161038db07a57bc7dbaa41
