### ISSUE TITLE
Moving to Docusaurus

### ISSUE THREAD

**Issue by Cadienvan** [Cadienvan/expirables#23]
As mentioned by @mateonunez in #22 , I'm opening this issue to move our docs from the current READMEs to a Docusaurus instance, hosted on Github Pages (?).

**Comment by mateonunez** [comment]
Yes, we can easily host the documentation page on GitHub pages. We can also deploy it on Vercel for free. Let's discuss about it, @Cadienvan.

**Comment by dabwebde** [comment]
Hi @Cadienvan @mateonunez I would be very interested in contributing to this issue for other collaborations
Regards D.

**Comment by Cadienvan** [comment]
Hi @jvProject if you know Docusaurus and want to handle this task I'd really LOVE to look at the PR!

**Comment by eppak** [comment]
Hello,
I'm making the first configuration of the docusaurus using "monorepo" suggested in the documentation, I will prepare a PR when ready. I will start with a base config, let me know if there are suggestions.

**Comment by Cadienvan** [comment]
Let's go!
