### ISSUE TITLE
Github page links not working

### ISSUE THREAD

**Issue by Cadienvan** [Cadienvan/expirables#29]
Hey @eppak thank you for the awesome work.
A thing I noticed after merging the PR is: the links for the single Expirable data structures lead to a 404.

I hope to have some time during the week to check if, but it you manage to find some minutes I'd love to bring in a PR fixing this

**Comment by eppak** [comment]
Hello @Cadienvan for sure, can you explain me how to reproduce the issue? I tried to run locally and go directly to "/docs/map" and got the page, tried also the build locally.

Thanks

**Comment by Cadienvan** [comment]
If you get to https://cadienvan.github.io/expirables/ and try to click on any of the links, they bring you to 404 pages: https://cadienvan.github.io/expirables/src/Map/README.md

**Comment by eppak** [comment]
I found what is going on, if the pull I opened to fix contributors is still open I can commit the fix there (I will rename it to have a better doc of what done on it).

**Comment by Cadienvan** [comment]
As you are fixing both for yourself go for it!

**Comment by eppak** [comment]
Hello, I fixed the root readme, was pointing to old md files that I moved to new docs, can you let me know?
Thanks

P.S. maybe the pipeline is to check because now we need also the package folder for the md files.

**Comment by Cadienvan** [comment]
Resolved in **v1.6.6**
